DX-914: Don't set `:site_destination_dir`
Setting `:site_destination_dir` here may cause the following error if
the `options_hash` is `nil`:

```ruby
undefined method `[]=' for nil:NilClass (NoMethodError)
```